// Stub generated plugin registrant.
// The actual file is generated by `flutter pub get`.
import FlutterMacOS

func RegisterGeneratedPlugins(registry: FlutterPluginRegistry) {
    // Plugins are registered automatically when using the Flutter tool.
}
